spring:
  datasource:
    url: jdbc:h2:mem:bank_db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml

logging:
  file:
    path: src/main/resources/logs