name: Simple CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
        
      - name: Build with Maven
        run: mvn clean install

      - name: Run tests with Maven
        run: mvn test

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start services with Docker Compose
        run: docker-compose up -d

      - name: Shutdown Docker Compose services
        run: docker-compose down
